"""Backward-compatible facade over shared cypher_builder."""

from __future__ import annotations

from cypher_builder import (
    LOOKUP_INSTRUCTION_BY_EVENT_CYPHER,
    CypherQueryBuilder,
    GraphIntent,
    GraphQueryPlan,
    extract_entity_ids,
    extract_event_id,
    extract_instruction_ids,
    extract_payment_ids,
    extract_uuids,
    format_facet_aggregate_answer,
    instruction_count_filters_from_question,
    instruction_id_from_list_payments_question,
    instruction_status_filter_from_question,
    instruction_type_filter_from_question,
    is_alert_ranking_question,
    is_count_question,
    is_facet_aggregate_question,
    is_instruction_approver_via_payment_question,
    is_instruction_count_aggregate_question,
    is_instruction_group_by_status_question,
    is_largest_payment_question,
    is_max_payments_per_instruction_question,
    is_payment_amount_threshold_question,
    is_payment_count_aggregate_question,
    is_payment_group_by_status_question,
    is_payment_id_lookup_for_instruction_question,
    is_payment_total_amount_question,
    is_payment_value_date_question,
    is_payments_for_instruction_question,
    is_security_event_alert_count_question,
    is_security_event_alert_list_question,
    is_security_event_count_aggregate_question,
    lob_filter_from_question,
    normalize_read_only_cypher,
    parse_facet_aggregate,
    payment_aggregate_period_label,
    payment_amount_threshold_from_question,
    payment_status_filter_from_question,
    plan_graph_queries,
    plans_from_graph_query,
    ranking_period_label,
    records_to_rows,
    row_summary,
    validate_read_only_cypher,
)
from cypher_builder import load_graph_schema as _load_graph_schema

from chat_application.config import settings


def load_graph_schema() -> str:
    return _load_graph_schema(settings.graph_schema_path)


__all__ = [
    "CypherQueryBuilder",
    "GraphIntent",
    "GraphQueryPlan",
    "LOOKUP_INSTRUCTION_BY_EVENT_CYPHER",
    "extract_entity_ids",
    "extract_event_id",
    "extract_instruction_ids",
    "extract_payment_ids",
    "extract_uuids",
    "format_facet_aggregate_answer",
    "instruction_count_filters_from_question",
    "instruction_id_from_list_payments_question",
    "instruction_status_filter_from_question",
    "instruction_type_filter_from_question",
    "is_alert_ranking_question",
    "is_count_question",
    "is_facet_aggregate_question",
    "is_instruction_approver_via_payment_question",
    "is_instruction_count_aggregate_question",
    "is_instruction_group_by_status_question",
    "is_largest_payment_question",
    "is_max_payments_per_instruction_question",
    "is_payment_amount_threshold_question",
    "is_payment_count_aggregate_question",
    "is_payment_group_by_status_question",
    "is_payment_total_amount_question",
    "is_payment_value_date_question",
    "is_payment_id_lookup_for_instruction_question",
    "is_payments_for_instruction_question",
    "is_security_event_alert_count_question",
    "is_security_event_alert_list_question",
    "is_security_event_count_aggregate_question",
    "load_graph_schema",
    "lob_filter_from_question",
    "normalize_read_only_cypher",
    "parse_facet_aggregate",
    "payment_aggregate_period_label",
    "payment_amount_threshold_from_question",
    "payment_status_filter_from_question",
    "plan_graph_queries",
    "plans_from_graph_query",
    "ranking_period_label",
    "records_to_rows",
    "row_summary",
    "validate_read_only_cypher",
]
